### ISSUE TITLE
0.6.3 cannot be run from yarn workspace subdirectory

### ISSUE THREAD

**Issue by aaronjensen** [shellscape/webpack-nano#13] opened 2019-07-21 04:51 UTC
- Webpack Version: 4.36.1
- Operating System (or Browser): macOS 10.14.5
- Node Version: 10.16.0
- webpack-nano Version: 0.6.3

### How Do We Reproduce?

Clone this, and follow the instructions in the readme
https://github.com/aaronjensen/webpack-nano-0.6.3-subdirectory-repro

### Expected Behavior

It works

### Actual Behavior

It quits silently no matter what flags I pass. 0.6.2 works fine. 0.6.3 & 0.7.0 exhibit this behavior.

**Comment by shellscape** [comment] 2019-07-21 15:28
Thanks for reporting. That's very odd indeed. It must be a case we're not currently testing for. I'm happy to take a look, but that repo url is 404.

**Comment by aaronjensen** [comment] 2019-07-21 16:10
@shellscape oops, sorry, should be public now.

**Comment by shellscape** [comment] 2019-07-21 16:15
Thanks. I'm not a yarn user. How do I properly initialize this repo?

**Comment by shellscape** [comment] 2019-07-21 16:29
Confirmed that this happened because of a regression in the latest version of `import-local`. The issue has been reported and there's a PR waiting for approval to fix it. In the mean time I'll see about downgrading that module to resolve it.

**Comment by shellscape** [comment] 2019-07-21 16:33
Fixed in 1faa7d5d51f36616bb291620d53185f56120c3c4 🍺 

Use 0.7.1 to get around that bug in `import-local`.

**Closed by shellscape** 2019-07-21 16:33 UTC
Labels: c⁴ ⋅ need more info

**Comment by aaronjensen** [comment] 2019-07-21 16:38
Thank you!
